default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_development

test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  # Render automatically provides DATABASE_URL. 
  # This line tells Rails to use that connection string.
  url: <%= ENV['DATABASE_URL'] %>