default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_development
  host: localhost

test:
  <<: *default
  database: blog_app_test
  host: localhost

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>